<?php
			
/* Generated by the CoffeeCup Web Editor - www.coffeecup.com */
			
/*
Description....
			
			
			
			
@created:           20/12/2014 - 09:13:12
@today:             20/12/2014
@project:           Untitled
@path:              /Users/Marcus/Localhost/labs/countup/index.php
			
@author:            Your name
@company:           Your company
@Copyright:         A copyright notice

@version:           $Revision:$
*/


?>
